server:
  port: 0

spring:
  application:
    name: member-service
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: jgb
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#jwt:
#  secret: 1234567890jangguenbeommsaproject1234567890
#  access-token-expiration-minutes: 30
#  refresh-token-expiration-minutes: 600