server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/jgb1123/spring-cloud-config-practice

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

encrypt:
  key-store:
    location: file:/devEncryptionKey.jks
    password: jgb1123
    alias: encryptionKey